# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i5mHLZAsdhT-QvyFr_bvZH3JNM78QaG7
"""

import streamlit as st
import os
from PIL import Image
import subprocess
import shutil

def save_uploaded_file(uploaded_file):
    try:
        with open('/content/data/images/uploaded_image.jpg', 'wb') as f:
            shutil.copyfileobj(uploaded_file, f)
        return True
    except Exception as e:
        st.error(f"Error saving image: {e}")
        return False

def main():
    st.title("이미지 업로드 프로토타입")

    uploaded_file = st.file_uploader("이미지 파일을 업로드해주세요", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        st.image(uploaded_file, caption="업로드한 이미지", use_column_width=True)

        # Save the uploaded file to /content/data/images
        if save_uploaded_file(uploaded_file):
            st.success("이미지 업로드 및 저장 성공!")

            # Run main.py
            result = subprocess.run(["python", "main.py"], capture_output=True, text=True)

            # Display the result
            st.subheader("실행 결과:")
            st.write(result.stdout)
        else:
            st.error("이미지를 저장하는 도중 오류가 발생했습니다.")

if __name__ == "__main__":
    main()