# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HYniYzEgMRAHYMtbtGqj-Zl7nB1Mg6uW
"""

import streamlit as st

st.title("강아지 얼굴 인식 프로토타입")

# 단계 1: 이미지 업로드 및 레이블링
st.header("단계 1: 이미지 업로드 및 레이블링")
uploaded_image_1 = st.file_uploader("이미지 업로드", type=["jpg", "png", "jpeg"])
if uploaded_image_1 is not None:
    label_name = st.text_input("강아지의 레이블을 입력하세요:", value="알 수 없음")
    st.image(uploaded_image_1, caption="업로드한 이미지", use_column_width=True)
    if st.button("알려진 얼굴에 추가"):
        find_dog_face(uploaded_image_1)
        add_known_face(uploaded_image_1.name, label_name)
        st.success("강아지 얼굴이 알려진 얼굴 목록에 추가되었습니다!")

# 단계 2: 이미지 평가
st.header("단계 2: 이미지 평가")
uploaded_image_2 = st.file_uploader("평가할 이미지 업로드", type=["jpg", "png", "jpeg"])
if uploaded_image_2 is not None:
    st.image(uploaded_image_2, caption="업로드한 이미지", use_column_width=True)

    # 이미지에서 강아지 얼굴 검출
    detected_face = find_dog_face(uploaded_image_2)

    # 강아지 얼굴 검출 시
    if detected_face:
        st.write("강아지 얼굴이 검출되었습니다!")

        # 검출한 얼굴과 알려진 얼굴 비교
        name_labeling(uploaded_image_2)
    else:
        st.warning("강아지 얼굴을 검출하지 못했습니다.")